name: Deploy

on:
  push:
    branches: [ mainFrontend ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      # Setup key
      - name: Setup key
        run: |
          set -eu
          mkdir "$HOME/.ssh"
          echo "${{ secrets.key }}" > "$HOME/.ssh/key"
          chmod 600 "$HOME/.ssh/key"
          cd frontend
      # Install
      - name: Install packages
        run: npm ci
      # Build
      - name: Build
        run: npm run build --if-present
      # Deploy
      - name: Deploy
        run: cd dist && rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . travel-across-russia@95.154.70.73://home/travel-across-russia/frontend